spring:
  profiles:
    active: dev

 
zuul:
  prefix: /Ocash
  ignored-services: "*"
  routes:
    mydept.serviceId: xhh-provider-dept
    mydept.path: /**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
info:
  app.name: Ocash
  company.name: www.Ocash.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 9001

spring:
  profiles: dev
  application:
    name: xhh-zuul-gateway

 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
    registry-fetch-interval-seconds: 30
  instance:
    instance-id: gateway-9001.com
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
 
--- 

server:
  port: 9001

spring:
  profiles: test
  application:
    name: xhh-zuul-gateway
   
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
    registry-fetch-interval-seconds: 30
  instance:
    instance-id: gateway-9001.com
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
 
--- 

server:
  port: 9001

spring:
  profiles: prod
  application:
    name: xhh-zuul-gateway
   
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
    registry-fetch-interval-seconds: 30
  instance:
    instance-id: gateway-9001.com
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
