spring:
  profiles:
    active: dev

feign:
  hystrix:
    enabled: true
debug: true    
---

server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  registry-fetch-interval-seconds: 30
  instance:
    instance-id: xhh-acp-80
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  profiles: dev
  application:
    name: xhh-acp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.21.110:3306/clouddb01?characterEncoding=utf8              # 数据库名称
    username: root
    password: 1qaz@2wsx
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: 192.168.21.130              # ip地址
    port: 6379                         #端口号
    timeout: 3000                      #客户端超时时间单位是毫秒 默认是2000
    password: xhh
    #    cluster:
    #      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382     # 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382
    #      max-redirects: 6
    pool:
      max-active: 200
      min-idle: 0                       #最小空闲数
      max-wait: -1                      #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      maxTotal: 200
      max-idle: 200                     #最大空闲数

--- 

server:
  port: 80
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  registry-fetch-interval-seconds: 30
  instance:
    instance-id: xhh-acp-80
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  profiles: test
  application:
    name: xhh-acp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.21.110:3306/clouddb01?characterEncoding=utf8              # 数据库名称
    username: root
    password: 1qaz@2wsx
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: 192.168.21.130              # ip地址
    port: 6379                         #端口号
    timeout: 3000                      #客户端超时时间单位是毫秒 默认是2000
    password: xhh
    #    cluster:
    #      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382     # 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382
    #      max-redirects: 6
    pool:
      max-active: 200
      min-idle: 0                       #最小空闲数
      max-wait: -1                      #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      maxTotal: 200
      max-idle: 200                     #最大空闲数

---
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  registry-fetch-interval-seconds: 30
  instance:
    instance-id: xhh-acp-80
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true     #访问路径可以显示IP地址

spring:
  profiles: prod
  application:
    name: xhh-acp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.21.110:3306/clouddb01?characterEncoding=utf8              # 数据库名称
    username: root
    password: 1qaz@2wsx
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: 192.168.21.130              # ip地址
    port: 6379                         #端口号
    timeout: 3000                      #客户端超时时间单位是毫秒 默认是2000
    password: xhh
    #    cluster:
    #      nodes: 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382     # 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382
    #      max-redirects: 6
    pool:
      max-active: 200
      min-idle: 0                       #最小空闲数
      max-wait: -1                      #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
      maxTotal: 200
      max-idle: 200                     #最大空闲数
